friends = ["Myles", "Jonathan", "Fatty Ferd", 2, False]
print(friends[2])
print(friends[-1])
print(friends[1:4])
friends[1]= "baggy"
print(friends[0:])
luckyNumbers = [12, 923, 1, 234, 42, 234, 9]
print(luckyNumbers)
friends.extend(luckyNumbers)
print(friends)
friends.append("Crilly")
print(friends)
friends.insert(1, "Benin")
print(friends)
friends.remove("baggy")
print(friends)
friends.clear()
print(friends)
luckyNumbers.pop()
print(luckyNumbers)
print(luckyNumbers.index(1))
print(luckyNumbers.count(1))
luckyNumbers.sort()
print(luckyNumbers)
luckyNumbers.reverse()
print(luckyNumbers)
luckyNumbers = friends.copy()
print(luckyNumbers)